[project]
name = "pyLibMeshb"
version = "0.1.7"
description = "Read/write mesh and solution files in Gamma Mesh Format (.mesh/.meshb/.sol/.solb)."
readme = "README.md"
authors = [
    { name = "Anthony Ricciardi", email = "vtpasquale@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.21",
]

classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
]

[project.urls]
Homepage = "https://github.com/vtpasquale/pyLibMeshb"

[project.optional-dependencies]
test = [
    "pytest>=8.0",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"pyLibMeshb" = ["*.so", "*.dll", "*.h"]

[tool.setuptools]
zip-safe = false