[project]
name = "pyLibMeshb"
version = "0.1.1"
description = "Python bindings for LibMeshb - the Gamma Mesh Format"
readme = "README.md"
authors = [
    { name = "Anthony Ricciardi", email = "vtpasquale@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.1",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"pyLibMeshb" = ["*.so", "*.dll", "*.h"]

[tool.setuptools]
zip-safe = false